language: python
python:
  - 3.6
  - 3.7
install:
  - pip install --upgrade setuptools
  - pip install -r requirements-dev.txt
  - pip install codecov
  - python setup.py develop

script:
  - make cov
  - python setup.py check -rms

after_success:
  - codecov

